### PR TITLE
Fix array to string conversion

### PR DESCRIPTION
**Pull request by robinkanters**
Regression introduced in 6f1447a60f068c89d345ceee32025a51dd630f1c

### CODE REVIEW

**Comment by sideshowcecil** [comment]
+1

**Comment by vpassapera** [comment]
+1

**Comment by xeroxzone** [comment]
+1

**Comment by robinkanters** [comment]
Temporary solution:
Make a strict dependency on `"phpunit/php-token-stream": "1.4.6"`, then remove that once a fix is released.

**Comment by rtheunissen** [comment]
Duplicate of #53

**Comment by mangelsnc** [comment]
+1

**Comment by luketarplin** [comment]
+1 Blocking our CI tool from approving packages

**Comment by anroots** [comment]
Affecting us, too. @robinkanters temporary solution works.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.

**Pull request closed without merging**
